language: python
python:
 # - "2.7"
#  - "3.3"
  - "3.4"

before_install:
 - sudo apt-get update
 - sudo apt-get install -y python-software-properties
 - sudo add-apt-repository -y ppa:chris-lea/node.js
 - sudo apt-get update
 - sudo apt-get install nodejs
 - sudo npm install -g bower
 - sudo npm install -g grunt-cli
install:
 - pip install -U setuptools
 - pip install -r requirements.txt #fix versions
 - python setup.py develop
 - pip install -U pytest pytest-cov coveralls webtest #install test deps
 - (cd ./atramhasis/static/admin && bower install)
 - (cd ./atramhasis/static/admin && sudo npm install)
before_script:
 - (cd ./atramhasis/static/admin && grunt -v build)
script:
 - py.test --cov atramhasis --cov-report term-missing tests
build_image: shippable/minv2:beta 
